### ISSUE TITLE
Use StreamField to define form fields

### ISSUE THREAD

**Issue by lohmander** [torchbox/wagtailsurveys#6]
Using a StreamField would allow for more flexibility and provide a more suitable interface for each respective field type.

Each field would be a block, which would also make it possible to add other kinds of content between fields (which has been a use case that has come up for us).

**Comment by m1kola** [comment]
I'm closing this issue, because the project is now deprecated and we are not planning to add any new features. There are some related issues in the Wagtail itself:

* https://github.com/wagtail/wagtail/issues/4485
* https://github.com/wagtail/wagtail/issues/1564
